modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="bossghost"
version="1.0.0"
displayName="Thai Ghost - Pee Boss Khakoh"
description='''
ผีพี่บอสขาโก่ง - ผีไทยวิ่งเร็ว ออกล่าผู้เล่นตอนกลางคืน ขึ้นที่สูงไม่ได้
'''

[[dependencies.bossghost]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bossghost]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
